// <auto-generated />
using CPRG214.Assets.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CPRG214.Assets.Data.Migrations
{
    [DbContext(typeof(AssetsContext))]
    partial class AssetsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CPRG214.Assets.Domain.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.ToTable("Asset");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetTypeId = 1,
                            Description = "Laptop 16gb ram",
                            Manufacturer = "Dell",
                            Model = "Inspiron",
                            SerialNumber = "K47839J999",
                            TagNumber = "59T2V22"
                        },
                        new
                        {
                            Id = 2,
                            AssetTypeId = 1,
                            Description = "Desktop 16GB ram",
                            Manufacturer = "Acer",
                            Model = "Aspire",
                            SerialNumber = "NXMQLLAAA0054",
                            TagNumber = "VN7591G"
                        },
                        new
                        {
                            Id = 3,
                            AssetTypeId = 2,
                            Description = "Full HD Gaming",
                            Manufacturer = "Acer",
                            Model = "Nitro",
                            SerialNumber = "ADLKNNE009AFD883-1",
                            TagNumber = "GH7591G-23"
                        },
                        new
                        {
                            Id = 4,
                            AssetTypeId = 2,
                            Description = "UHD 4K",
                            Manufacturer = "LG",
                            Model = "UltraFine",
                            SerialNumber = "KJHEFNG0067-55",
                            TagNumber = "GH7591G-23"
                        },
                        new
                        {
                            Id = 5,
                            AssetTypeId = 3,
                            Description = "High-Fidelity and Secure",
                            Manufacturer = "Cisco",
                            Model = "8845 VoIP",
                            SerialNumber = "ADFJ8AEEF000000JU88",
                            TagNumber = "J7J7M28"
                        },
                        new
                        {
                            Id = 6,
                            AssetTypeId = 3,
                            Description = "Videoconference ready desktop",
                            Manufacturer = "Polycom",
                            Model = "VVX601 IP",
                            SerialNumber = "LKJEI00001",
                            TagNumber = "7m3LKUE8890-1"
                        });
                });

            modelBuilder.Entity("CPRG214.Assets.Domain.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AssetType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Monitor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Phone"
                        });
                });

            modelBuilder.Entity("CPRG214.Assets.Domain.Asset", b =>
                {
                    b.HasOne("CPRG214.Assets.Domain.AssetType", null)
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
